#!/bin/sh
#
# @name AERODROME VTOL EFI PENGUIN B
#
# @type Standard VTOL
# @class VTOL
#
# @maintainer Yaniv Sneh <yanivs@aerodrome-ops.com>
#
# @output MAIN1 Aileron left
# @output MAIN2 A-tail left
# @output MAIN3 Pusher motor
# @output MAIN4 A-tail right
# @output MAIN5 motor 1
# @output MAIN6 motor 2
# @output MAIN7 motor 3
# @output MAIN8 motor 4
# @output AUX3 Aileron right
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.vtol_defaults



set MAV_TYPE 22

#set MIXER aerodrome_penguin_b_efi_vtol
#set MIXER_AUX pass

set MIXER quad_x
set MIXER_AUX vtol_AAERT

set PWM_OUT 1234
